import type { CompileTarget, HeraldManifest } from "./types.js";

// ── Helpers ────────────────────────────────────────────────────────────────
function header(tool: string): string {
  return `<!-- Generated by Herald CLI — do not edit manually.
     Source of truth: .herald/
     Regenerate: npx herald-agents compile ${tool}
-->\n\n`;
}

function projectSummary(m: HeraldManifest): string {
  return [
    `# ${m.project.name}`,
    "",
    m.project.description,
    "",
    m.project.framework ? `**Framework**: ${m.project.framework}` : null,
    m.project.language  ? `**Language**: ${m.project.language}`   : null,
  ].filter(l => l !== null).join("\n");
}

// ── Compile targets ────────────────────────────────────────────────────────
export const VENDORS: CompileTarget[] = [
  // ── Claude Code ──────────────────────────────────────────────────────────
  {
    id: "claude",
    label: "Claude Code (CLAUDE.md)",
    outputPath: "CLAUDE.md",
    generate(manifest, context) {
      return header("claude") +
`${projectSummary(manifest)}

---

${context}

---

*This file is generated from \`.herald/\`. Edit \`.herald/context/\` instead.*
`;
    },
  },

  // ── Cursor ───────────────────────────────────────────────────────────────
  {
    id: "cursor",
    label: "Cursor (.cursor/rules/herald.mdc)",
    outputPath: ".cursor/rules/herald.mdc",
    generate(manifest, context) {
      return `---
description: ${manifest.project.description}
globs: ["**/*"]
alwaysApply: true
---

${context}
`;
    },
  },

  // ── GitHub Copilot ────────────────────────────────────────────────────────
  {
    id: "copilot",
    label: "GitHub Copilot (.github/copilot-instructions.md)",
    outputPath: ".github/copilot-instructions.md",
    generate(manifest, context) {
      return header("copilot") +
`${projectSummary(manifest)}

---

${context}
`;
    },
  },

  // ── Gemini CLI ────────────────────────────────────────────────────────────
  {
    id: "gemini",
    label: "Gemini CLI (GEMINI.md)",
    outputPath: "GEMINI.md",
    generate(manifest, context) {
      return header("gemini") +
`${projectSummary(manifest)}

---

${context}
`;
    },
  },

  // ── Windsurf ─────────────────────────────────────────────────────────────
  {
    id: "windsurf",
    label: "Windsurf (.windsurfrules)",
    outputPath: ".windsurfrules",
    generate(_manifest, context) {
      return context;
    },
  },

  // ── Roo Code ─────────────────────────────────────────────────────────────
  {
    id: "roo",
    label: "Roo Code (.clinerules)",
    outputPath: ".clinerules",
    generate(_manifest, context) {
      return context;
    },
  },

  // ── Aider ─────────────────────────────────────────────────────────────────
  {
    id: "aider",
    label: "Aider (CONVENTIONS.md)",
    outputPath: "CONVENTIONS.md",
    generate(manifest, context) {
      return `# ${manifest.project.name} — Conventions\n\n${context}\n`;
    },
  },

  // ── AGENTS.md ─────────────────────────────────────────────────────────────
  {
    id: "agents",
    label: "AGENTS.md (universal fallback)",
    outputPath: "AGENTS.md",
    generate(manifest, context) {
      return `# ${manifest.project.name} — Agent Guidelines

> This file is generated from \`.herald/\`. Edit \`.herald/context/\` instead.
> Regenerate: \`npx herald-agents compile agents\`

${manifest.project.description}
${manifest.project.framework ? `\n**Framework**: ${manifest.project.framework}` : ""}

---

${context}

---

*Full HERALD config in \`.herald/\` — compatible with Claude Code, Cursor, Copilot, Gemini, and more.*
`;
    },
  },
];

export function getVendor(id: string): CompileTarget | undefined {
  return VENDORS.find(v => v.id === id);
}
